# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - golint
    - govet
    - staticcheck
    - godot
    - goimports
    - gofumpt
    - gofmt
    - misspell
    - whitespace
    - goconst
    - gocritic
    - nolintlint
    - nakedret
    - forbidigo
    - wsl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  nakedret:
    # Make an issue if func has more lines of code than this setting, and it has naked returns.
    max-func-lines: 8
