AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: dev

Resources:
  PaymentsService:
    Type: AWS::Serverless::Application
    Properties:
      Location: go/api/payments/infra/template.yml
      Parameters:
        Stage: !Ref Stage
  UsersService:
    Type: AWS::Serverless::Application
    Properties:
      Location: go/api/users/infra/template.yml
      Parameters:
        Stage: !Ref Stage
