AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  This template creates the api resources for the payments service.

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true
Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.

Resources:
  GetPaymentFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/lambdas/get-payment/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /payments/{id}
            Method: GET
      Environment:
        Variables:
          STAGE: !Ref Stage
          PAYMENTS_TABLE_NAME: !Sub "{{resolve:ssm:/payments/${Stage}/ddb/TableName:1}}"
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub "payments/${Stage}/*"
        - DynamoDBCrudPolicy:
            TableName: !Sub "{{resolve:ssm:/payments/${Stage}/ddb/TableName:1}}"

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub "ApplicationInsights-SAM-${AWS::StackName}"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Sub "ApplicationInsights-SAM-${AWS::StackName}"
      AutoConfigurationEnabled: "true"
    DependsOn: ApplicationResourceGroup
Outputs:
  PaymentsService:
    Description: API Gateway endpoint URL for Prod environment for Payments Service
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  GetPaymentFn:
    Description: Get Payment Lambda Function ARN
    Value: !GetAtt GetPaymentFn.Arn
