AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  This template creates the api resources for the users service.

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true
Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.

Resources:
  GetUserFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/lambdas/get-user/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/{id}
            Method: GET
      Environment:
        Variables:
          STAGE: !Ref Stage
          USERS_TABLE_NAME: !Sub "{{resolve:ssm:/users/${Stage}/ddb/TableName:1}}"
          REGION: !Ref AWS::Region
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub "users/${Stage}/*"
        - DynamoDBCrudPolicy:
            TableName: !Sub "{{resolve:ssm:/users/${Stage}/ddb/TableName:1}}"

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub "ApplicationInsights-SAM-${AWS::StackName}"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Sub "ApplicationInsights-SAM-${AWS::StackName}"
      AutoConfigurationEnabled: true
    DependsOn: ApplicationResourceGroup
Outputs:
  UsersService:
    Description: API Gateway endpoint URL for Prod environment for Users Service
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  GetUserFn:
    Description: Get User Lambda Function ARN
    Value: !GetAtt GetUserFn.Arn
