AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  This template creates the database resources for the users service.

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.

Resources:
  UsersDB:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Storing resources names to SSM
  UsersTableName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/users/${Stage}/ddb/TableName"
      Type: "String"
      Value: !Ref UsersDB
      Description: "Users Table name"
  UsersTableArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/users/${Stage}/ddb/TableArn"
      Type: "String"
      Value: !GetAtt UsersDB.Arn
      Description: "Users Table ARN"
  UsersTableStreamArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/users/${Stage}/ddb/StreamArn"
      Type: "String"
      Value: !GetAtt UsersDB.StreamArn
      Description: "Users DynamoDB Stream ARN"
  UsersTableStreamName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/users/${Stage}/ddb/StreamName"
      Type: "String"
      Value: !Select
        - 2
        - !Split
          - "/"
          - !Select
            - 5
            - !Split [":", !GetAtt UsersDB.StreamArn]
      Description: "Users DynamoDB Stream name"
