AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: >-
  This application creates a users service using serverless technologies such as API Gateway, Lambda etc.

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.

Resources:
  Api:
    Type: "AWS::Serverless::Application"
    Properties:
      Location: "api.template.yml"
      Parameters:
        Stage: !Ref Stage
    DependsOn: Database
  Database:
    Type: "AWS::Serverless::Application"
    Properties:
      Location: "db.template.yml"
      Parameters:
        Stage: !Ref Stage
