AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  This template creates the database resources for the payments service.

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.

Resources:
  PaymentsDB:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Storing resources names to SSM
  PaymentsTableName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/payments/${Stage}/ddb/TableName"
      Type: "String"
      Value: !Ref PaymentsDB
      Description: "Payments Table name"
  PaymentsTableArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/payments/${Stage}/ddb/TableArn"
      Type: "String"
      Value: !GetAtt PaymentsDB.Arn
      Description: "Payments Table ARN"
  PaymentsTableStreamArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/payments/${Stage}/ddb/StreamArn"
      Type: "String"
      Value: !GetAtt PaymentsDB.StreamArn
      Description: "Payments DynamoDB Stream ARN"
  PaymentsTableStreamName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/payments/${Stage}/ddb/StreamName"
      Type: "String"
      Value: !Select
        - 2
        - !Split
          - "/"
          - !Select
            - 5
            - !Split [":", !GetAtt PaymentsDB.StreamArn]
      Description: "Payments DynamoDB Stream name"
