name: Production Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stack-deploy:
    name: Stack Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      # url: https://github.com // TODO add url to production environment
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache SST
        id: cache-sst
        uses: actions/cache@v3
        with:
          path: .sst
          key: sst-production

      - name: Install dependencies
        run: pnpm install

      - name: Deploy stack
        run: pnpm run deploy --stage=prod
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
